"""create coins and associations

Revision ID: dfcd719bbcfe
Revises: c33e0ef08727
Create Date: 2024-09-21 03:28:00.877830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfcd719bbcfe'
down_revision: Union[str, None] = 'c33e0ef08727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_coin_associations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.UUID(), nullable=False),
    sa.Column('min_rate', sa.Float(), nullable=True),
    sa.Column('max_rate', sa.Float(), nullable=True),
    sa.Column('rate_percentage_growth', sa.Float(), nullable=True),
    sa.Column('rate_percentage_declines', sa.Float(), nullable=True),
    sa.Column('saved_rate_to_compare', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coin_id'], ['coins.id'], name=op.f('fk_user_coin_associations_coin_id_coins')),
    sa.ForeignKeyConstraint(['user_id'], ['tg_users.id'], name=op.f('fk_user_coin_associations_user_id_tg_users')),
    sa.PrimaryKeyConstraint('user_id', 'coin_id', 'id', name=op.f('pk_user_coin_associations'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_coin_associations')
    # ### end Alembic commands ###
