"""user upd

Revision ID: c20ec40bc5ce
Revises: 295daef4703e
Create Date: 2024-09-21 01:03:26.091677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20ec40bc5ce'
down_revision: Union[str, None] = '295daef4703e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    op.add_column('tg_users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('tg_users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_users', 'created_at')
    op.drop_column('tg_users', 'updated_at')
    op.drop_column('tg_users', 'is_superuser')
    # ### end Alembic commands ###
